//
//  ScreenshotUITests.swift
//  MyFeelsLikeUITests
//
//  Drives the app in demo mode (-UITestDemo) and captures App Store
//  screenshots via fastlane snapshot. Run with: `fastlane screenshots`.
//
//  Requires fastlane's SnapshotHelper.swift to be a member of this target
//  (generated by `fastlane snapshot init`) so setupSnapshot/snapshot exist.
//

import XCTest

final class ScreenshotUITests: XCTestCase {

    override func setUpWithError() throws {
        continueAfterFailure = false
    }

    @MainActor
    func testCaptureScreenshots() throws {
        let app = XCUIApplication()
        app.launchArguments += ["-UITestDemo"]
        setupSnapshot(app)
        app.launch()

        // Wait until the canned data has loaded (the Rate button appears).
        let rate = app.buttons["rateButton"]
        XCTAssertTrue(rate.waitForExistence(timeout: 20), "Main screen never appeared")

        // 1 — 24-hour graph (start screen)
        snapshot("01_today")

        // 2 — 10-day graph
        app.swipeLeft()
        sleep(1)
        snapshot("02_tenday")

        // 3 — Table
        app.swipeLeft()
        sleep(1)
        snapshot("03_table")

        // 4 — Rate Feels Like sheet
        rate.tap()
        sleep(1)
        snapshot("04_rate")
        if app.buttons["Cancel"].waitForExistence(timeout: 3) {
            app.buttons["Cancel"].tap()
            sleep(1)
        }

        // 5 — Places
        app.buttons["placesButton"].tap()
        sleep(1)
        snapshot("05_places")
    }
}
